server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fuar_dbb
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  websocket:
    allowed-origins: "http://localhost:3000,http://localhost:3001"
    endpoint: /ws
    destination-prefixes: /app
    broker-prefix: /topic, /queue
    heartbeat:
      client-interval: 10000
      server-time: 10000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
